pmnt fail and image embed for success
mchrzanka/banfflogcabin-project pull request #64
Opened 2022-11-24 15:20 UTC by krussell23

2022-11-24 15:29 UTC, krussell23 commented
route added as well

2022-11-24 19:21 UTC, mchrzanka submitted a review, later dismissed

2022-11-24 19:23 UTC, mchrzanka requested changes
Hey Kevin, please look at the figma design that Justin made and match your code to that.

2022-11-24 20:03 UTC, krussell23 commented
image optomized box added

2022-11-25 01:56 UTC, mchrzanka approved these changes

2022-11-25 01:56 UTC, merged